import type { MajlisCardProps, WorldCardProps } from "../types";

export const mockSessions: MajlisCardProps[] = [
  {
    id: "1",
    title: "جلسة لتحفيظ سورة البقرة من المصحف الكريم - جزء ١",
    description:
      "ابدأ رحلتك في حفظ سورة البقرة خطوة بخطوة مع تلاوة دقيقة من المصحف الكريم وفي أجواء روحانية محفزة",
    totalPlaces: 32,
    currentAttendees: 20,
    status: "current",
  },
  {
    id: "2",
    title: "أساسيات التصميم الجرافيكي الحديث وتطبيقاته",
    description:
      "ورشة عمل تفاعلية لاكتساب المهارات الأساسية في التصميم الجرافيكي وتطبيقاته العملية.",
    totalPlaces: 50,
    currentAttendees: 45,
    status: "upcoming",
  },
  {
    id: "3",
    title: "تطوير تطبيقات الويب المتقدمة باستخدام React",
    description:
      "تعلم أحدث التقنيات وأفضل الممارسات في بناء واجهات المستخدم التفاعلية.",
    totalPlaces: 100,
    currentAttendees: 80,
    status: "past",
  },
  {
    id: "4",
    title: "ورشة عمل: القيادة الفعالة وإدارة الفرق",
    description:
      "اكتشف أسرار القيادة الناجحة وكيفية تحفيز فريقك لتحقيق الأهداف المشتركة.",
    totalPlaces: 25,
    currentAttendees: 25,
    status: "upcoming",
  },
  {
    id: "5",
    title: "مقدمة في الذكاء الاصطناعي وتعلم الآلة",
    description: "استكشف المفاهيم الأساسية للذكاء الاصطناعي وكيف يغير العالم من حولنا.",
    totalPlaces: 120,
    currentAttendees: 95,
    status: "current",
  },
  {
    id: "6",
    title: "تطوير تطبيقات الموبايل باستخدام Flutter",
    description: "ابنِ تطبيقك الأول للهواتف الذكية بنظامي Android و iOS باستخدام قاعدة كود واحدة.",
    totalPlaces: 60,
    currentAttendees: 40,
    status: "upcoming",
  },
  {
    id: "7",
    title: "أساسيات التمويل الشخصي والاستثمار الذكي",
    description: "تعلم كيفية إدارة أموالك، التخطيط للمستقبل، وتجنب الديون العقيمة.",
    totalPlaces: 40,
    currentAttendees: 38,
    status: "past",
  },
  {
    id: "8",
    title: "تحسين محركات البحث (SEO) للمبتدئين",
    description: "طرق عملية لزيادة زوار موقعك وتصدر نتائج البحث الأولى محلياً وعالمياً.",
    totalPlaces: 30,
    currentAttendees: 15,
    status: "upcoming",
  },
  {
    id: "9",
    title: "نادي الكتاب: مناقشة رواية الخيميائي",
    description: "جلسة أدبية تفاعلية لمناقشة الرموز والمعاني العميقة في رواية الخيميائي الشهيرة.",
    totalPlaces: 15,
    currentAttendees: 12,
    status: "current",
  },
  {
    id: "10",
    title: "كتابة المحتوى التسويقي المقنع وصناعة الهوية",
    description: "تعلم كيف تكتب نصوصاً تبيع وتصنع هوية بصرية ولفظية فريدة لعلامتك التجارية.",
    totalPlaces: 80,
    currentAttendees: 72,
    status: "upcoming",
  },
];

export const mockWorlds: WorldCardProps[] = [
  {
    id: "1",
    name: "عالم التقنية",
    description: "مساحة مخصصة لمناقشة أحدث التقنيات والبرمجيات والمستجدات التقنية.",
    memberCount: 1250,
    coverImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "2",
    name: "الفنون والتصميم",
    description: "تجمع للمصممين والفنانين لتبادل الخبرات والأعمال الملهمة والتوجيه.",
    memberCount: 840,
    coverImage: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "3",
    name: "ريادة الأعمال",
    description: "شارك أفكارك وتعرف على رواد الأعمال والمستثمرين في منطقتك.",
    memberCount: 2100,
    coverImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "4",
    name: "القراءة والأدب",
    description: "نادي كتاب افتراضي لمناقشة أفضل الروايات والكتب الأدبية والفلسفية.",
    memberCount: 560,
    coverImage: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "5",
    name: "عالم اللياقة والصحة",
    description: "كل ما يخص الرياضة، التغذية السليمة، ونمط الحياة الصحي المتوازن.",
    memberCount: 1540,
    coverImage: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "6",
    name: "السفر والمغامرات",
    description: "استكشف ثقافات جديدة وشارك تجارب السفر والنصائح لأفضل الوجهات.",
    memberCount: 980,
    coverImage: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "7",
    name: "الموسيقى والصوتيات",
    description: "ملتقى لعشاق الموسيقى ومصممي الصوت لتبادل الألحان والمواهب.",
    memberCount: 720,
    coverImage: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "8",
    name: "الطهي وفنون المطبخ",
    description: "شارك وصفاتك المفضلة وتعلم أسرار الطهي من مختلف مطابخ العالم.",
    memberCount: 1100,
    coverImage: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "9",
    name: "عالم الألعاب الإلكترونية",
    description: "تجمع للاعبين لمناقشة ألعاب الفيديو المفضلة والبطولات المحلية.",
    memberCount: 3200,
    coverImage: "https://images.unsplash.com/photo-1385829365295-ab7cd4ad7217?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "10",
    name: "العلوم والابتكار",
    description: "استكشف أسرار الكون وناقش أحدث الاكتشافات العلمية والنظريات.",
    memberCount: 450,
    coverImage: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "11",
    name: "التصوير الفوتوغرافي",
    description: "شارك لقطاتك الفنية وتعرف على أحدث تقنيات التصوير والكاميرات.",
    memberCount: 670,
    coverImage: "https://images.unsplash.com/photo-1452780212940-6f5c0d14d848?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "12",
    name: "التنمية الذاتية",
    description: "مساحة لتبادل مهارات التواصل والتخطيط وتطوير الذات وبناء العادات.",
    memberCount: 1890,
    coverImage: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "13",
    name: "التاريخ والآثار",
    description: "رحلة عبر الزمن لاستكشاف الحضارات القديمة والقصص التاريخية العظيمة.",
    memberCount: 390,
    coverImage: "https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "14",
    name: "اللغات والترجمة",
    description: "تعلم لغات جديدة وشارك في جلسات المحادثة الجماعية لتحسين مهاراتك.",
    memberCount: 820,
    coverImage: "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "15",
    name: "عالم السينما والأفلام",
    description: "عشاق الفن السابع يجتمعون لنقد ومناقشة أحدث الأفلام والمسلسلات الكلاسيكية.",
    memberCount: 1430,
    coverImage: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "16",
    name: "السيارات والمحركات",
    description: "كل ما يخص عشاق السرعة والسيارات الكلاسيكية والحديثة وتعديلاتها.",
    memberCount: 950,
    coverImage: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "17",
    name: "البرمجة وهندسة البرمجيات",
    description: "مساحة للمطورين لحل المشكلات البرمجية ومشاركة المشاريع مفتوحة المصدر.",
    memberCount: 2800,
    coverImage: "https://images.unsplash.com/photo-1484417894907-623942c8ea29?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "18",
    name: "الاستثمار والعملات الرقمية",
    description: "شارك تحليلات السوق المالي والعملات المشفرة ومشاريع البلوكشين.",
    memberCount: 1670,
    coverImage: "https://images.unsplash.com/photo-1621416894569-0f39ed31d247?auto=format&fit=crop&q=80&w=800",
  },
];
